##
#@package main_application
#@brief This package delivers functions for signing PDF documents using an RSA (4096) private key. 
# Additionally, it enables users to verify PDF documents using an RSA (4096-bit) public key and the embedded digital signature. 
# The digital signature is generated by hashing the contents of the PDF document pages. 
#
#The `main_application` package contains the following modules:
#- `main.py` - Handles the main application logic.
#- `gui.py` - Provides the graphical user interface.
#- `signAndVerifyPDF.py` - Responsible for PDF documents signing and verification using digital signatures.
#